### ISSUE TITLE
Introduce integration test with Cloud Logging Processor

### ISSUE THREAD

**Issue by myurtoglu** [abcxyz/lumberjack#224] opened 2022-04-19 22:39 UTC
Currently, in integration tests, we use Remote Processor but not the Cloud Logging Processor [by providing `AUDIT_CLIENT_BACKEND_REMOTE_ADDRESS` but not `BACKEND_CLOUDLOGGING_DEFAULT_PROJECT ` or `BACKEND_CLOUDLOGGING_PROJECT`](https://github.com/abcxyz/lumberjack/blob/91287239c1a41be51311c92b7b6fcd169488bb43/terraform/modules/ci-run-with-server/main.tf#L21).

Given the current tendency to not use the Remote Processor, but instead to use the Cloud Logging Processor, we should either reconfigure our testing scheme, or add a new test that does use Cloud Logging Processor and not use Remote Processor.

**Comment by yolocs** [comment] 2022-07-28 19:17
Duplicate of https://github.com/abcxyz/lumberjack/issues/224

**Closed by yolocs** 2022-07-28 19:17 UTC
Labels: enhancement, test
